x-common-variables: &common-variables
  AUTH_HOST: auth-service
  AUTH_PORT: 8080
  API_HOST: api-service
  API_PORT: 3000

services:
  auth:
    platform: linux/amd64
    image: ghcr.io/mini-roostico/api-web-auth:master
    container_name: auth-service
    hostname: auth-service
    restart: always
    environment:
      <<: *common-variables
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]

  api:
    platform: linux/amd64
    image: ghcr.io/mini-roostico/api-web-api:master
    container_name: api-service
    hostname: api-service
    restart: always
    environment:
      <<: *common-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]

  frontend-service:
    platform: linux/amd64
    image: ghcr.io/mini-roostico/web-frontend:master
    container_name: web-frontend
    hostname: web-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
      auth:
        condition: service_healthy
    environment:
      <<: *common-variables
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]