x-common-variables: &common-variables
  AUTH_HOST: auth-service
  AUTH_PORT: 8180
  API_HOST: api-service
  API_PORT: 3000
  REDIS_HOST: redis
  REDIS_PORT: 6379
  MONGO_HOST: mongodb
  MONGO_PORT: 27017
  AT_PRIVATE: /run/secrets/at_private.pem
  RT_PRIVATE: /run/secrets/rt_private.pem

services:
  auth:
    platform: linux/amd64
    image: ghcr.io/mini-roostico/api-web-auth:master
    container_name: auth-service
    hostname: auth-service
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - "./secrets:/run/secrets:ro"
    environment:
      <<: *common-variables
      DOCS: /usr/src/app/auth/swagger.json
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://auth-service:8180/health"]

  api:
    platform: linux/amd64
    image: ghcr.io/mini-roostico/api-web-api:master
    container_name: api-service
    hostname: api-service
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - "./secrets:/run/secrets:ro"
    environment:
      <<: *common-variables
      DOCS: /usr/src/app/api/swagger.json
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://api-service:3000/health" ]

  frontend-service:
    platform: linux/amd64
    image: ghcr.io/mini-roostico/web-frontend:master
    container_name: web-frontend
    hostname: web-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
      auth:
        condition: service_healthy
    environment:
      <<: *common-variables
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  # Redis service, used for api rate limiting
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]